### ISSUE TITLE
Total Received shows wrong amount

### ISSUE THREAD

**Issue by Oilburner09** [ergoplatform/explorer-frontend#100]
Transactions section "Total Received" is the sum of the received amounts and the balance value from the sent amounts combined. This is unexpected behavior. 
https://explorer.ergoplatform.com/en/addresses/9enyYkKLkhhN5ePWFWfQ149ezZ6CNLitnntEK11b5AUbauZL1K9
![image](https://user-images.githubusercontent.com/43079596/108295650-493faa00-7155-11eb-82ab-9142f27a584e.png)

**Comment by oskin1** [comment]
Resolved.
