### ISSUE TITLE
Improve Error Message 

### ISSUE THREAD

**Issue by eezis** [ergoplatform/explorer-frontend#103]
If a user attempts to transfer from gate.io, the transaction goes into one state -- it might have been 'waiting' -- and then to 'pending.' If the user clicks through they see this message:

Transaction with this ID was not found, or it has not entered Mempool yet

It would be much better if it said something like, "Your transaction has been initiated, but has not yet entered the Mempool, this is normal for this stage of the transaction. More data will be available when a Transaction ID is assigned."

<img width="659" alt="ergo-error-vague" src="https://user-images.githubusercontent.com/2529528/109348997-7ca7c600-7832-11eb-9012-5b4ed32dd554.png">

**Comment by deadit** [comment]
Hi. Thanks for feedback, but I am don’t know initiated transaction or no. I just check transaction I’d at mempool and blocks.

**Comment by eezis** [comment]
Here's more info. At an exchange, when a user starts a transfer, they are typically provided with a link. A good one would look like this:  

https://explorer.ergoplatform.com/en/transactions/7b16...4d5. 

The user would go to the explorer and see the TX progress. But when gate_io fails, the link looks like this:

https://explorer.ergoplatform.com/en/transactions/pending...

So at the server you can trap the error -- I do that at my site, I parse the path to see what caused the 404 and take corrective action if possible or custom messages if not. So if you see "pending" or something similar you can add more data to the original message. Something like: 

"If you are attempting to transfer from an exchange and this error has not resolved in 10 minutes, then you may wish to contact their support desk."
