### ISSUE TITLE
'ERROR: bigint out of range' when viewing no.1 from rich list

### ISSUE THREAD

**Issue by AnonNoMore** [ergoplatform/explorer-frontend#115]
When viewing the number 1 from the rich list, the server responds with `Unknown error: ERROR: bigint out of range`, resulting in de Explorer infinitely showing the message 'Fetching data...'. Over on Discord @oskin1 said it's simply a matter of updating the frontend to call the v1 api, which does not have this issue.

The rich list page:
https://explorer.ergoplatform.com/en/addresses/9fPiW45mZwoTxSwTLLXaZcdekqi72emebENmScyTGsjryzrntUe

Underlying api call (with error):
https://api.ergoplatform.com/addresses/9fPiW45mZwoTxSwTLLXaZcdekqi72emebENmScyTGsjryzrntUe

**Comment by deadit** [comment]
Thank you. Will take a look. Sorry for the delay

**Comment by deadit** [comment]
Done at https://github.com/ergoplatform/explorer-frontend/commit/ac13a348f997c39c45dbba7fb9b0c893cde09d22
