### ISSUE TITLE
Migrate to AddressesAPIv1

### ISSUE THREAD

**Issue by yasha-black** [ergoplatform/explorer-frontend#132]
The current AddressSummary page hangs on heavy requests:
https://explorer.ergoplatform.com/en/addresses/9fPiW45mZwoTxSwTLLXaZcdekqi72emebENmScyTGsjryzrntUe

This should be helpful:

https://api.ergoplatform.com/api/v1/docs/#operation/getApiV1AddressesP1BalanceConfirmed

**Comment by deadit** [comment]
Already
