### ISSUE TITLE
Mobile sidebar Rich List overlap

### ISSUE THREAD

**Issue by a34tjkx** [ergoplatform/explorer-frontend#164]
While viewing the Rich List on mobile, the main window's text covers the sidebar. See attached.
![sidebar_richlist](https://user-images.githubusercontent.com/97005815/156840775-949a0465-7a4f-4545-800a-8d7b18a58f25.png)

**Comment by deadit** [comment]
Thank you!

**Comment by a34tjkx** [comment]
It works perfectly on Chrome, Brave, and Firefox for me. Nice job!
