### ISSUE TITLE
Ability to connect wallet to explorer with dapp connector to easily load your own addresses

### ISSUE THREAD

**Issue by NoahErgo** [ergoplatform/explorer-frontend#181]
All wallets associated with your wallet could be displayed and selected

**Comment by NoahErgo** [comment]
With this connect wallet view having an address book would be useful to save and label addresses to identify friends, other wallets you interact with frequently

**Comment by deadit** [comment]
Do you see any explorer with this functionality?

**Comment by deadit** [comment]
need more specific for this UX. If you really think this feature really needed can you write the whole UX? You can create a board in Miro/figma with some template/user scenario how you see this functionality.

**Comment by NoahErgo** [comment]
I think probably this feature is better handled at wallet level. Can ignore this suggestion
